### ISSUE TITLE
Issue: Expected workspace to have one lwc folder

### ISSUE THREAD

**Issue by lynguyenkhang** [salesforcecli/plugin-lightning-dev#174]
### Summary

After completing the steps in this [Preview Components with Local Dev (Beta)
](https://developer.salesforce.com/docs/platform/lwc/guide/get-started-test-components.html), I run script ```sf lightning dev app -o MY_SANDBOX```. It causes an error

```
Error (1): Expected workspace to have one lwc folder
```

And my sfdx project includes the folder *force-app/main/default*. Please, help me to resolve this issue. Thank you.

### Steps To Reproduce:

1. Complete the steps in this article [article](https://developer.salesforce.com/docs/platform/lwc/guide/get-started-test-components.html),

1. Run script ```sf lightning dev app -o MY_SANDBOX```

### Expected result

The CLI should run successfully.

### Actual result

It returns an error

```
Error (1): Expected workspace to have one lwc folder
```

_Describe what actually happened instead_.

### Additional information

_Feel free to attach a screenshot_.

**VS Code Version**:

**SFDX CLI Version**:

**OS and version**:

**Comment by albertocabo** [comment]
Same here

**Comment by lynguyenkhang** [comment]
Forget to mention that I've been used Code Builder (web-based Visual Studio Code)

**Comment by khawkins** [comment]
Thanks for bringing this issue to our attention. A couple of things to note here:

- > Forget to mention that I've been used Code Builder (web-based Visual Studio Code)
    
    We don't yet support Code Builder for Local Dev, sorry to say. We are investigating how we can support Code Builder use cases in a future release. No timelines yet. #safeharbor

- That said, this error will also come up in a local VSCode project scenario, when your project does not have the `force-app/main/default/lwc/` folder in the local project. We'll look at providing a more descriptive error message guarding against this condition. In the meantime, if you add the `force-app/main/default/lwc/` folder to your project, this error should go away—although in this case it's a nominal fix, since without any LWCs in your local project, Local Dev isn't going to do anything for you. You'll want to either retrieve the LWC(s) from your org that you're developing locally, or create a new LWC, deploy it to your org, and then launch Local Dev to see your local changes as you make them.

Let us know if that doesn't describe your setup, and we can work with you to see what else may be going on.

**Comment by albertocabo** [comment]
@khawkins  in my case I'm working in local VSCode and I do have a force-app/main/default/lwc/ folder

**Comment by tparaiso** [comment]
I have the same error with multiple folder (the second folder is set at false) 
![CleanShot 2024-10-04 at 21 04 19](https://github.com/user-attachments/assets/8cd6c2d9-521d-461d-b0cb-c528a400b708)

In sfdx-project.json : 
![CleanShot 2024-10-04 at 21 05 15](https://github.com/user-attachments/assets/ae6290b5-90ed-4764-902a-d49b423c113c)

I run the command : sf lightning dev app
I get : Error (1): Expected workspace to have one lwc folder

I remove my second folder from sfdx-project.json : 
![CleanShot 2024-10-04 at 21 06 20](https://github.com/user-attachments/assets/09aa7f30-b09f-4ba6-8a2b-76d3c3db50f9)
It's Ok Lightning Dev App started. 

It's shame that only the default folder at true can be used.

**Comment by khawkins** [comment]
Sounds like there are a few lingering issues around this part of the functionality. We'll take a look and report back here on options available that you can go forward with. Thanks for the feedback so far!

**Comment by grbeazley** [comment]
I'm facing the same issue as @tparaiso where we have multiple package directories in the same SFDX project with LWCs present in more than one of the directories.

**Comment by dustinrediess-sikich** [comment]
Same error for me. In my case, however, I have a second package directory configured in sfdx-project.json but it does not contain an LWC folder. Slightly different situation than the example @tparaiso provided. 

If I remove that second folder from the packageDirectories list I, too, can run Local Dev successfully. 

![image](https://github.com/user-attachments/assets/b2387712-1d82-44c0-9407-c1912974c9f1)

**Comment by szymon-halik** [comment]
I am facing the same issue. Support for multi package monorepos is a must

**Comment by ravijayaramappa** [comment]
Thanks every one who has reported this issue so far. We are working on a fix and will update here shortly.

**Comment by amurashincertinia** [comment]
@ravijayaramappa, is it not too late to extend support for a more flexible directory structure beyond the rigid 4-level `dir/dir/dir/lwc`?

In some of our projects the directory structure differs from this format.

For example:
`force-lib/common/lwc`
`force-wip/lwc`

Projects may also have dependencies listed in the `sfdx-project.json`:

```json
{
  "packageDirectories": [
    {
      "path": "node_modules/some-other-component-library/force-lib",
      "default": false
    },
    {
      "path": "force-wip",
      "default": false
    },
    {
      "path": "force-lib",
      "default": true
    },
    {
      "path": "force-app",
      "default": false
    }
  ]
}
```

**Comment by ravijayaramappa** [comment]
@amurashincertinia with the latest version of the plugin, any level of nesting of `lwc` folder should be supported. Please open a separate issue if you have a usecase that is not working.
