### ISSUE TITLE
Error (10): this.config.plugins.filter is not a function

### ISSUE THREAD

**Issue by ravnarayananpaypal** [salesforcecli/plugin-lightning-dev#247]
When i try the command **sf lightning dev app**,  the system is prompting me to select type of device and name of application. After selecting the app name , i am getting below error.

Error (10): this.config.plugins.filter is not a function

**Comment by maliroteh-sf** [comment]
@ravnarayananpaypal please follow the template for reporting a potential bug/issue from [here](https://github.com/salesforcecli/plugin-lightning-dev/issues/new?assignees=&labels=&projects=&template=Bug_report.md) and provide the necessary details that it asks for. We need these details to aid us in further investigations.
